version: "2.1"

services:
  proxy_reconf:
    build: .
    command: /app/startServer.sh
    container_name: proxy_reconf
    volumes:  
      - ${NGINX_VOLUME}:/etc/nginx:rw
    networks:
      - op_data_datanetwork
    ports:
      - "8000:8000"
      - "90:90"
    restart: on-failure
networks:
  op_data_datanetwork:
    external: true
