spring:
   boot.admin: #Spring Boot Admin Config    
      url: http://localhost:18100
      username: operations
      password: changeIt!
      client.metadata.user.name: ${spring.boot.admin.username}
      client.metadata.user.password: $spring.boot.admin.password}   